// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiqx8fXPxFmYszNJzC2bTQ4BTsoLkJhdc',
    appId: '1:426679585080:web:4a57c7a1098000de5319cd',
    messagingSenderId: '426679585080',
    projectId: 'g-parking-314202',
    authDomain: 'g-parking-314202.firebaseapp.com',
    databaseURL: 'https://g-parking-314202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'g-parking-314202.appspot.com',
    measurementId: 'G-2MLB48EJT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnCYNgOGitIYJZFcCyWAwPU6aURrbQUR0',
    appId: '1:426679585080:android:7f6bf801db4af93f5319cd',
    messagingSenderId: '426679585080',
    projectId: 'g-parking-314202',
    databaseURL: 'https://g-parking-314202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'g-parking-314202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTgP2-akJVtsxZADkG8nKZBCYaum9PAkg',
    appId: '1:426679585080:ios:dc1425feffc77c6a5319cd',
    messagingSenderId: '426679585080',
    projectId: 'g-parking-314202',
    databaseURL: 'https://g-parking-314202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'g-parking-314202.appspot.com',
    iosClientId: '426679585080-kf5qofqiep55sgiigeqdipf6s5r3jpos.apps.googleusercontent.com',
    iosBundleId: 'com.example.gParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTgP2-akJVtsxZADkG8nKZBCYaum9PAkg',
    appId: '1:426679585080:ios:dc1425feffc77c6a5319cd',
    messagingSenderId: '426679585080',
    projectId: 'g-parking-314202',
    databaseURL: 'https://g-parking-314202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'g-parking-314202.appspot.com',
    iosClientId: '426679585080-kf5qofqiep55sgiigeqdipf6s5r3jpos.apps.googleusercontent.com',
    iosBundleId: 'com.example.gParking',
  );
}
